/**
 * Vite plugin: сканирует `public/images/home/**` → `src/lib/homePhotos.generated.ts`.
 * Любые jpg/jpeg/png/webp/avif в корне или подпапках попадают в слайдшоу главной.
 */
import fs from 'node:fs'
import path from 'node:path'
import type { Plugin } from 'vite'

const IMAGE_EXT = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif'])

function walkImages(dir: string, root: string, out: string[] = []): string[] {
  if (!fs.existsSync(dir)) return out
  for (const name of fs.readdirSync(dir)) {
    if (name.startsWith('.')) continue
    const full = path.join(dir, name)
    const st = fs.statSync(full)
    if (st.isDirectory()) {
      walkImages(full, root, out)
      continue
    }
    const ext = path.extname(name).toLowerCase()
    if (!IMAGE_EXT.has(ext)) continue
    out.push(path.relative(root, full).split(path.sep).join('/'))
  }
  return out
}

function categoryFromRel(rel: string): string {
  const parts = rel.split('/')
  if (parts.length >= 2) return parts[0].toLowerCase()
  const base = parts[0].toLowerCase()
  const m = base.match(/^(bzmp|show|race|coursing|donino)[-_]/i)
  return m ? m[1].toLowerCase() : 'home'
}

export function writeHomePhotosManifest(publicHomeDir: string, outFile: string): number {
  const rels = walkImages(publicHomeDir, publicHomeDir).sort((a, b) =>
    a.localeCompare(b, 'en'),
  )
  const entries = rels.map((rel) => {
    const id = rel.replace(/\.[^.]+$/, '').replace(/[^\w]+/g, '-')
    const src = `/images/home/${rel}`
    const category = categoryFromRel(rel)
    return { id, src, category }
  })

  const body = `/* AUTO-GENERATED by vite-plugin-home-photos — do not edit.
 * Source: frontend/public/images/home/** (jpg/png/webp/avif, включая подпапки).
 * Перескан: npm run dev / vite build, или после добавления файлов в папку.
 */
export interface HomePhotoGenerated {
  id: string
  src: string
  category: string
}

export const HOME_PHOTOS_GENERATED: HomePhotoGenerated[] = ${JSON.stringify(entries, null, 2)}
`

  fs.mkdirSync(path.dirname(outFile), { recursive: true })
  const prev = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : ''
  if (prev !== body) fs.writeFileSync(outFile, body, 'utf8')
  return entries.length
}

export function homePhotosPlugin(opts: {
  publicHomeDir: string
  outFile: string
}): Plugin {
  const { publicHomeDir, outFile } = opts
  let scanned = false

  const scan = (reason: string) => {
    const n = writeHomePhotosManifest(publicHomeDir, outFile)
    if (!scanned) {
      console.log(`[home-photos] ${n} image(s) → ${path.relative(process.cwd(), outFile)} (${reason})`)
      scanned = true
    }
  }

  return {
    name: 'home-photos-manifest',
    enforce: 'pre',
    buildStart() {
      scan('build')
    },
    configureServer(server) {
      scan('dev')
      const watchRoot = publicHomeDir
      if (fs.existsSync(watchRoot)) {
        server.watcher.add(watchRoot)
      }
      server.watcher.on('all', (_event, file) => {
        if (!file) return
        const norm = file.replace(/\\/g, '/')
        if (!norm.includes('/images/home')) return
        if (norm.endsWith('homePhotos.generated.ts')) return
        scanned = false
        scan('watch')
        // Подсказать клиенту перезагрузку после новых файлов
        server.ws.send({ type: 'full-reload' })
      })
    },
  }
}
