name = "procoursing-stats"
main = "backend/src/worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 2 * * 1"]  # Weekly on Monday at 2 AM UTC

[[d1_databases]]
binding = "DB"
database_name = "pc-db"
database_id = "a5d6d4ad-7fc5-41b4-a33b-05f4daa382d4"
