/** Веса и утилиты рейтинга выставочных наград (conformation). */

/**
 * Канонические ключи счётчиков. Алиасы протокола (ЛПП (BOB), R.CAC…) → сюда.
 * Порядок SHOW_AWARD_ORDER = приоритет для best_award и tie-break.
 */
/** От крутых к менее крутым (карточки, best_award, tie-break). */
export const SHOW_AWARD_ORDER = [
  'BIS',
  'BIG',
  'BIS_JUNIOR',
  'BIS_VETERAN',
  'BIS_PUPPY',
  'BIS_BABY',
  'BOB',
  'BOS',
  'LYU',
  'LV',
  'LSH',
  'LB',
  'CACIB',
  'R_CACIB',
  'CAC',
  'JCAC',
  'VCAC',
  'CHRKF',
  'YCHRKF',
  'VCHRKF',
  'P_RUSSIA',
  'P_MOSCOW',
  'YP_RUSSIA',
  'YP_MOSCOW',
  'VP_RUSSIA',
  'VP_MOSCOW',
  'KCHK',
  'KCHP',
  'YKCHK',
  'YKCHP',
  'VKCHK',
  'VKCHP',
  'CW',
  'R_CAC',
  'R_JCAC',
  'R_VCAC',
  'SS',
  'YSS',
  'VSS',
] as const

export type ShowAwardKey = (typeof SHOW_AWARD_ORDER)[number]

export type ShowTitleCounts = Record<ShowAwardKey, number>

/** Ключи для фильтров «минимум» в рейтинге (не все 30 полей). */
export const SHOW_FILTER_AWARD_KEYS: ShowAwardKey[] = [
  'BIS',
  'BIG',
  'BIS_JUNIOR',
  'BOB',
  'BOS',
  'CACIB',
  'CAC',
  'JCAC',
  'CW',
  'CHRKF',
  'KCHK',
  'KCHP',
]

/** Веса rank_score: главный ринг → порода → сертификаты → резервы → дипломы дня. */
export const SHOW_AWARD_WEIGHTS: Record<ShowAwardKey, number> = {
  BIS: 10_000,
  BIG: 5_000,
  BIS_JUNIOR: 3_500,
  BIS_VETERAN: 3_200,
  BIS_PUPPY: 2_800,
  BIS_BABY: 2_500,
  BOB: 2_000,
  BOS: 1_500,
  LB: 800,
  LSH: 800,
  LYU: 900,
  LV: 850,
  CACIB: 500,
  CAC: 100,
  JCAC: 80,
  VCAC: 70,
  CW: 40,
  R_CACIB: 200,
  R_CAC: 40,
  R_JCAC: 30,
  R_VCAC: 25,
  CHRKF: 60,
  YCHRKF: 50,
  VCHRKF: 45,
  KCHK: 35,
  YKCHK: 30,
  VKCHK: 28,
  KCHP: 35,
  YKCHP: 30,
  VKCHP: 28,
  P_RUSSIA: 55,
  P_MOSCOW: 50,
  YP_RUSSIA: 45,
  YP_MOSCOW: 40,
  VP_RUSSIA: 42,
  VP_MOSCOW: 38,
  SS: 15,
  YSS: 12,
  VSS: 12,
}

/**
 * Короткая подпись на бейдже — как привыкли в РФ (ЛПП, не «BOB/ЛПП»).
 * Латиница остаётся там, где её так и говорят: BIS, BIG, CAC…
 */
export const SHOW_AWARD_BADGE: Record<ShowAwardKey, string> = {
  BIS: 'BIS',
  BIG: 'BIG',
  BIS_JUNIOR: 'BIS-Ю',
  BIS_VETERAN: 'BIS-В',
  BIS_PUPPY: 'BIS-Щ',
  BIS_BABY: 'BIS-Б',
  BOB: 'ЛПП',
  BOS: 'ЛППП',
  LB: 'ЛБ',
  LSH: 'ЛЩ',
  LYU: 'ЛЮ',
  LV: 'ЛВ',
  CACIB: 'CACIB',
  CAC: 'CAC',
  JCAC: 'JCAC',
  VCAC: 'VCAC',
  CW: 'CW',
  R_CACIB: 'R.CACIB',
  R_CAC: 'R.CAC',
  R_JCAC: 'R.JCAC',
  R_VCAC: 'R.VCAC',
  CHRKF: 'ЧРКФ',
  YCHRKF: 'ЮЧРКФ',
  VCHRKF: 'ВЧРКФ',
  KCHK: 'КЧК',
  YKCHK: 'ЮКЧК',
  VKCHK: 'ВКЧК',
  KCHP: 'КЧП',
  YKCHP: 'ЮКЧП',
  VKCHP: 'ВКЧП',
  P_RUSSIA: 'П «России»',
  P_MOSCOW: 'П Москвы',
  YP_RUSSIA: 'ЮП «России»',
  YP_MOSCOW: 'ЮП Москвы',
  VP_RUSSIA: 'ВП «России»',
  VP_MOSCOW: 'ВП Москвы',
  SS: 'СС',
  YSS: 'ЮСС',
  VSS: 'ВСС',
}

export const SHOW_AWARD_LABELS: Record<ShowAwardKey, string> = {
  BIS: 'Лучшая собака выставки (Best in Show)',
  BIG: 'Лучшая в группе FCI (Best in Group)',
  BIS_JUNIOR: 'Лучший юниор выставки (BIS Junior) — главный ринг, не ЛЮ породы',
  BIS_VETERAN: 'Лучший ветеран выставки (BIS Veteran) — главный ринг, не ЛВ породы',
  BIS_PUPPY: 'Лучший щенок выставки (BIS Puppy) — главный ринг, не ЛЩ породы',
  BIS_BABY: 'Лучший беби выставки (BIS Baby) — главный ринг, не ЛБ породы',
  BOB: 'Лучший представитель породы (ЛПП / BOB)',
  BOS: 'Лучший противоположного пола (ЛППП / BOS)',
  LB: 'Лучший беби породы (ЛБ)',
  LSH: 'Лучший щенок породы (ЛЩ)',
  LYU: 'Лучший юниор породы (ЛЮ)',
  LV: 'Лучший ветеран породы (ЛВ)',
  CACIB: 'CACIB — кандидат в интернациональные чемпионы красоты (FCI)',
  CAC: 'CAC — кандидат в чемпионы России по красоте',
  JCAC: 'JCAC — кандидат в юные чемпионы России по красоте',
  VCAC: 'VCAC — кандидат в чемпионы-ветераны по красоте',
  CW: 'CW — победитель класса',
  R_CACIB: 'R.CACIB — резервный CACIB',
  R_CAC: 'R.CAC — резервный CAC',
  R_JCAC: 'R.JCAC — резервный JCAC',
  R_VCAC: 'R.VCAC — резервный VCAC',
  CHRKF: 'ЧРКФ — чемпион РКФ (диплом на выставке)',
  YCHRKF: 'ЮЧРКФ — юный чемпион РКФ (диплом на выставке)',
  VCHRKF: 'ВЧРКФ — ветеран-чемпион РКФ (диплом на выставке)',
  KCHK: 'КЧК — кандидат в чемпионы клуба (породы с НКП)',
  YKCHK: 'ЮКЧК — юный кандидат в чемпионы клуба',
  VKCHK: 'ВКЧК — ветеран — кандидат в чемпионы клуба',
  KCHP: 'КЧП — кандидат в чемпионы породы (породы без НКП)',
  YKCHP: 'ЮКЧП — юный кандидат в чемпионы породы',
  VKCHP: 'ВКЧП — ветеран — кандидат в чемпионы породы',
  P_RUSSIA: 'П «России» — победитель выставки «Россия»',
  P_MOSCOW: 'П Москвы — победитель выставки / Кубка Москвы',
  YP_RUSSIA: 'ЮП «России» — юный победитель «России»',
  YP_MOSCOW: 'ЮП Москвы — юный победитель Москвы',
  VP_RUSSIA: 'ВП «России» — ветеран-победитель «России»',
  VP_MOSCOW: 'ВП Москвы — ветеран-победитель Москвы',
  SS: 'СС — сертификат соответствия',
  YSS: 'ЮСС — юный сертификат соответствия',
  VSS: 'ВСС — ветеранский сертификат соответствия',
}

/** Категория для UI: крутые / сертификаты / титулы дня. */
export type ShowAwardCategory = 'prestige' | 'certificate' | 'diploma'

export const SHOW_AWARD_CATEGORY_ORDER: ShowAwardCategory[] = [
  'prestige',
  'certificate',
  'diploma',
]

export const SHOW_AWARD_CATEGORY_LABEL: Record<ShowAwardCategory, string> = {
  prestige: 'Крутые',
  certificate: 'Сертификаты',
  diploma: 'Титулы дня',
}

export const SHOW_AWARD_CATEGORY: Record<ShowAwardKey, ShowAwardCategory> = {
  BIS: 'prestige',
  BIG: 'prestige',
  BIS_JUNIOR: 'prestige',
  BIS_VETERAN: 'prestige',
  BIS_PUPPY: 'prestige',
  BIS_BABY: 'prestige',
  BOB: 'prestige',
  BOS: 'prestige',
  LB: 'prestige',
  LSH: 'prestige',
  LYU: 'prestige',
  LV: 'prestige',
  CACIB: 'certificate',
  R_CACIB: 'certificate',
  CAC: 'certificate',
  JCAC: 'certificate',
  VCAC: 'certificate',
  CW: 'certificate',
  R_CAC: 'certificate',
  R_JCAC: 'certificate',
  R_VCAC: 'certificate',
  CHRKF: 'diploma',
  YCHRKF: 'diploma',
  VCHRKF: 'diploma',
  KCHK: 'diploma',
  YKCHK: 'diploma',
  VKCHK: 'diploma',
  KCHP: 'diploma',
  YKCHP: 'diploma',
  VKCHP: 'diploma',
  P_RUSSIA: 'diploma',
  P_MOSCOW: 'diploma',
  YP_RUSSIA: 'diploma',
  YP_MOSCOW: 'diploma',
  VP_RUSSIA: 'diploma',
  VP_MOSCOW: 'diploma',
  SS: 'diploma',
  YSS: 'diploma',
  VSS: 'diploma',
}

export const EMPTY_SHOW_TITLES: ShowTitleCounts = Object.fromEntries(
  SHOW_AWARD_ORDER.map((k) => [k, 0]),
) as ShowTitleCounts
