/* AUTO-GENERATED by vite-plugin-home-photos — do not edit.
 * Source: frontend/public/assets/home/** (jpg/png/webp/avif, включая подпапки).
 * Перескан: npm run dev / vite build, или после добавления файлов в папку.
 */
export interface HomePhotoGenerated {
  id: string
  src: string
  category: string
}

export const HOME_PHOTOS_GENERATED: HomePhotoGenerated[] = [
  {
    "id": "bot-banner",
    "src": "/assets/home/bot-banner.webp",
    "category": "home"
  }
]
