/* AUTO-GENERATED by vite-plugin-home-photos — do not edit.
 * Source: frontend/public/images/home/** (jpg/png/webp/avif, включая подпапки).
 * Перескан: npm run dev / vite build, или после добавления файлов в папку.
 */
export interface HomePhotoGenerated {
  id: string
  src: string
  category: string
}

export const HOME_PHOTOS_GENERATED: HomePhotoGenerated[] = [
  {
    "id": "bzmp-01",
    "src": "/images/home/bzmp-01.jpg",
    "category": "bzmp"
  },
  {
    "id": "bzmp-02",
    "src": "/images/home/bzmp-02.jpg",
    "category": "bzmp"
  },
  {
    "id": "bzmp-04",
    "src": "/images/home/bzmp-04.jpg",
    "category": "bzmp"
  },
  {
    "id": "bzmp-05",
    "src": "/images/home/bzmp-05.jpg",
    "category": "bzmp"
  },
  {
    "id": "race-01",
    "src": "/images/home/race-01.jpg",
    "category": "race"
  },
  {
    "id": "race-02",
    "src": "/images/home/race-02.jpg",
    "category": "race"
  },
  {
    "id": "race-03",
    "src": "/images/home/race-03.jpg",
    "category": "race"
  },
  {
    "id": "race-04",
    "src": "/images/home/race-04.jpg",
    "category": "race"
  },
  {
    "id": "race-05",
    "src": "/images/home/race-05.jpg",
    "category": "race"
  },
  {
    "id": "race-06",
    "src": "/images/home/race-06.jpg",
    "category": "race"
  },
  {
    "id": "race-07",
    "src": "/images/home/race-07.jpg",
    "category": "race"
  },
  {
    "id": "race-08",
    "src": "/images/home/race-08.jpg",
    "category": "race"
  },
  {
    "id": "race-09",
    "src": "/images/home/race-09.jpg",
    "category": "race"
  },
  {
    "id": "race-12",
    "src": "/images/home/race-12.jpg",
    "category": "race"
  },
  {
    "id": "race-13",
    "src": "/images/home/race-13.jpg",
    "category": "race"
  },
  {
    "id": "race-15",
    "src": "/images/home/race-15.jpg",
    "category": "race"
  }
]
