import {
  Calendar,
  MapPin,
  Users,
  Trophy,
  Medal,
  Gauge,
  Search,
  SlidersHorizontal,
  ChevronDown,
  ChevronRight,
  X,
  Menu,
  Share2,
  Sun,
  Moon,
  ExternalLink,
  Flag,
  Star,
  TrendingUp,
  Award,
  PawPrint,
  Zap
} from 'lucide-react'

export const Icons = {
  calendar: Calendar,
  location: MapPin,
  club: Users,
  championship: Trophy,
  medal: Medal,
  speed: Gauge,
  search: Search,
  filters: SlidersHorizontal,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  close: X,
  menu: Menu,
  share: Share2,
  sun: Sun,
  moon: Moon,
  externalLink: ExternalLink,
  flag: Flag,
  achievement: Star,
  trend: TrendingUp,
  award: Award,
  paw: PawPrint,
  speedFlash: Zap,
} as const
